/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OwnerPanelRouteRouteImport } from './routes/owner-panel/route'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as DownloadFileIdRouteImport } from './routes/download/$fileId'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as GamesSlugRouteImport } from './routes/games/$slug'
import { Route as OwnerPanelIndexRouteImport } from './routes/owner-panel/index'
import { Route as OwnerPanelSettingsRouteImport } from './routes/owner-panel/settings'
import { Route as AdminGamesIndexRouteImport } from './routes/admin/games/index'
import { Route as AdminGamesIdRouteImport } from './routes/admin/games/$id'
import { Route as AdminGamesNewRouteImport } from './routes/admin/games/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDownloadFileIdRouteImport } from './routes/api/download/$fileId'
import { Route as ApiMediaKeyRouteImport } from './routes/api/media/$key'
import { Route as OwnerPanelGamesIndexRouteImport } from './routes/owner-panel/games/index'
import { Route as OwnerPanelGamesIdRouteImport } from './routes/owner-panel/games/$id'
import { Route as OwnerPanelGamesNewRouteImport } from './routes/owner-panel/games/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPanelRouteRoute = OwnerPanelRouteRouteImport.update({
  id: '/owner-panel',
  path: '/owner-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadFileIdRoute = DownloadFileIdRouteImport.update({
  id: '/download/$fileId',
  path: '/download/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPanelIndexRoute = OwnerPanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerPanelRouteRoute,
} as any)
const OwnerPanelSettingsRoute = OwnerPanelSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerPanelRouteRoute,
} as any)
const AdminGamesIndexRoute = AdminGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGamesIdRoute = AdminGamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGamesNewRoute = AdminGamesNewRouteImport.update({
  id: '/games/new',
  path: '/games/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadFileIdRoute = ApiDownloadFileIdRouteImport.update({
  id: '/api/download/$fileId',
  path: '/api/download/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaKeyRoute = ApiMediaKeyRouteImport.update({
  id: '/api/media/$key',
  path: '/api/media/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPanelGamesIndexRoute = OwnerPanelGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => OwnerPanelRouteRoute,
} as any)
const OwnerPanelGamesIdRoute = OwnerPanelGamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => OwnerPanelRouteRoute,
} as any)
const OwnerPanelGamesNewRoute = OwnerPanelGamesNewRouteImport.update({
  id: '/games/new',
  path: '/games/new',
  getParentRoute: () => OwnerPanelRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/owner-panel': typeof OwnerPanelRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/latest': typeof LatestRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/search': typeof SearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/download/$fileId': typeof DownloadFileIdRoute
  '/games/$slug': typeof GamesSlugRoute
  '/owner-panel/settings': typeof OwnerPanelSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/games/': typeof GamesIndexRoute
  '/owner-panel/': typeof OwnerPanelIndexRoute
  '/admin/games/$id': typeof AdminGamesIdRoute
  '/admin/games/new': typeof AdminGamesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/download/$fileId': typeof ApiDownloadFileIdRoute
  '/api/media/$key': typeof ApiMediaKeyRoute
  '/owner-panel/games/$id': typeof OwnerPanelGamesIdRoute
  '/owner-panel/games/new': typeof OwnerPanelGamesNewRoute
  '/admin/games/': typeof AdminGamesIndexRoute
  '/owner-panel/games/': typeof OwnerPanelGamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/latest': typeof LatestRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/search': typeof SearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/download/$fileId': typeof DownloadFileIdRoute
  '/games/$slug': typeof GamesSlugRoute
  '/owner-panel/settings': typeof OwnerPanelSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/games': typeof GamesIndexRoute
  '/owner-panel': typeof OwnerPanelIndexRoute
  '/admin/games/$id': typeof AdminGamesIdRoute
  '/admin/games/new': typeof AdminGamesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/download/$fileId': typeof ApiDownloadFileIdRoute
  '/api/media/$key': typeof ApiMediaKeyRoute
  '/owner-panel/games/$id': typeof OwnerPanelGamesIdRoute
  '/owner-panel/games/new': typeof OwnerPanelGamesNewRoute
  '/admin/games': typeof AdminGamesIndexRoute
  '/owner-panel/games': typeof OwnerPanelGamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/owner-panel': typeof OwnerPanelRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/latest': typeof LatestRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/search': typeof SearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/download/$fileId': typeof DownloadFileIdRoute
  '/games/$slug': typeof GamesSlugRoute
  '/owner-panel/settings': typeof OwnerPanelSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/games/': typeof GamesIndexRoute
  '/owner-panel/': typeof OwnerPanelIndexRoute
  '/admin/games/$id': typeof AdminGamesIdRoute
  '/admin/games/new': typeof AdminGamesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/download/$fileId': typeof ApiDownloadFileIdRoute
  '/api/media/$key': typeof ApiMediaKeyRoute
  '/owner-panel/games/$id': typeof OwnerPanelGamesIdRoute
  '/owner-panel/games/new': typeof OwnerPanelGamesNewRoute
  '/admin/games/': typeof AdminGamesIndexRoute
  '/owner-panel/games/': typeof OwnerPanelGamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/owner-panel'
    | '/$'
    | '/latest'
    | '/login'
    | '/projects'
    | '/search'
    | '/admin/settings'
    | '/api/upload'
    | '/download/$fileId'
    | '/games/$slug'
    | '/owner-panel/settings'
    | '/admin/'
    | '/games/'
    | '/owner-panel/'
    | '/admin/games/$id'
    | '/admin/games/new'
    | '/api/auth/$'
    | '/api/download/$fileId'
    | '/api/media/$key'
    | '/owner-panel/games/$id'
    | '/owner-panel/games/new'
    | '/admin/games/'
    | '/owner-panel/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/latest'
    | '/login'
    | '/projects'
    | '/search'
    | '/admin/settings'
    | '/api/upload'
    | '/download/$fileId'
    | '/games/$slug'
    | '/owner-panel/settings'
    | '/admin'
    | '/games'
    | '/owner-panel'
    | '/admin/games/$id'
    | '/admin/games/new'
    | '/api/auth/$'
    | '/api/download/$fileId'
    | '/api/media/$key'
    | '/owner-panel/games/$id'
    | '/owner-panel/games/new'
    | '/admin/games'
    | '/owner-panel/games'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/owner-panel'
    | '/$'
    | '/latest'
    | '/login'
    | '/projects'
    | '/search'
    | '/admin/settings'
    | '/api/upload'
    | '/download/$fileId'
    | '/games/$slug'
    | '/owner-panel/settings'
    | '/admin/'
    | '/games/'
    | '/owner-panel/'
    | '/admin/games/$id'
    | '/admin/games/new'
    | '/api/auth/$'
    | '/api/download/$fileId'
    | '/api/media/$key'
    | '/owner-panel/games/$id'
    | '/owner-panel/games/new'
    | '/admin/games/'
    | '/owner-panel/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  OwnerPanelRouteRoute: typeof OwnerPanelRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  LatestRoute: typeof LatestRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRoute
  SearchRoute: typeof SearchRoute
  ApiUploadRoute: typeof ApiUploadRoute
  DownloadFileIdRoute: typeof DownloadFileIdRoute
  GamesSlugRoute: typeof GamesSlugRoute
  GamesIndexRoute: typeof GamesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDownloadFileIdRoute: typeof ApiDownloadFileIdRoute
  ApiMediaKeyRoute: typeof ApiMediaKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-panel': {
      id: '/owner-panel'
      path: '/owner-panel'
      fullPath: '/owner-panel'
      preLoaderRoute: typeof OwnerPanelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/$fileId': {
      id: '/download/$fileId'
      path: '/download/$fileId'
      fullPath: '/download/$fileId'
      preLoaderRoute: typeof DownloadFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-panel/': {
      id: '/owner-panel/'
      path: '/'
      fullPath: '/owner-panel/'
      preLoaderRoute: typeof OwnerPanelIndexRouteImport
      parentRoute: typeof OwnerPanelRouteRoute
    }
    '/owner-panel/settings': {
      id: '/owner-panel/settings'
      path: '/settings'
      fullPath: '/owner-panel/settings'
      preLoaderRoute: typeof OwnerPanelSettingsRouteImport
      parentRoute: typeof OwnerPanelRouteRoute
    }
    '/admin/games/': {
      id: '/admin/games/'
      path: '/games'
      fullPath: '/admin/games/'
      preLoaderRoute: typeof AdminGamesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/games/$id': {
      id: '/admin/games/$id'
      path: '/games/$id'
      fullPath: '/admin/games/$id'
      preLoaderRoute: typeof AdminGamesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/games/new': {
      id: '/admin/games/new'
      path: '/games/new'
      fullPath: '/admin/games/new'
      preLoaderRoute: typeof AdminGamesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/$fileId': {
      id: '/api/download/$fileId'
      path: '/api/download/$fileId'
      fullPath: '/api/download/$fileId'
      preLoaderRoute: typeof ApiDownloadFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$key': {
      id: '/api/media/$key'
      path: '/api/media/$key'
      fullPath: '/api/media/$key'
      preLoaderRoute: typeof ApiMediaKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-panel/games/': {
      id: '/owner-panel/games/'
      path: '/games'
      fullPath: '/owner-panel/games/'
      preLoaderRoute: typeof OwnerPanelGamesIndexRouteImport
      parentRoute: typeof OwnerPanelRouteRoute
    }
    '/owner-panel/games/$id': {
      id: '/owner-panel/games/$id'
      path: '/games/$id'
      fullPath: '/owner-panel/games/$id'
      preLoaderRoute: typeof OwnerPanelGamesIdRouteImport
      parentRoute: typeof OwnerPanelRouteRoute
    }
    '/owner-panel/games/new': {
      id: '/owner-panel/games/new'
      path: '/games/new'
      fullPath: '/owner-panel/games/new'
      preLoaderRoute: typeof OwnerPanelGamesNewRouteImport
      parentRoute: typeof OwnerPanelRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminGamesIdRoute: typeof AdminGamesIdRoute
  AdminGamesNewRoute: typeof AdminGamesNewRoute
  AdminGamesIndexRoute: typeof AdminGamesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminGamesIdRoute: AdminGamesIdRoute,
  AdminGamesNewRoute: AdminGamesNewRoute,
  AdminGamesIndexRoute: AdminGamesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface OwnerPanelRouteRouteChildren {
  OwnerPanelSettingsRoute: typeof OwnerPanelSettingsRoute
  OwnerPanelIndexRoute: typeof OwnerPanelIndexRoute
  OwnerPanelGamesIdRoute: typeof OwnerPanelGamesIdRoute
  OwnerPanelGamesNewRoute: typeof OwnerPanelGamesNewRoute
  OwnerPanelGamesIndexRoute: typeof OwnerPanelGamesIndexRoute
}

const OwnerPanelRouteRouteChildren: OwnerPanelRouteRouteChildren = {
  OwnerPanelSettingsRoute: OwnerPanelSettingsRoute,
  OwnerPanelIndexRoute: OwnerPanelIndexRoute,
  OwnerPanelGamesIdRoute: OwnerPanelGamesIdRoute,
  OwnerPanelGamesNewRoute: OwnerPanelGamesNewRoute,
  OwnerPanelGamesIndexRoute: OwnerPanelGamesIndexRoute,
}

const OwnerPanelRouteRouteWithChildren = OwnerPanelRouteRoute._addFileChildren(
  OwnerPanelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  OwnerPanelRouteRoute: OwnerPanelRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  LatestRoute: LatestRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRoute,
  SearchRoute: SearchRoute,
  ApiUploadRoute: ApiUploadRoute,
  DownloadFileIdRoute: DownloadFileIdRoute,
  GamesSlugRoute: GamesSlugRoute,
  GamesIndexRoute: GamesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDownloadFileIdRoute: ApiDownloadFileIdRoute,
  ApiMediaKeyRoute: ApiMediaKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
